# List of superusers
superuser_usernames:
  - "mad"

# Used for express-session security
# Change it to anything you want 
session_secret: "some secret string"

# Secret key for the jwt system when logging in
jwt_secret: "some secret string"

# Public google recaptcha key
recaptcha_key: "recaptchaPublicKey"

# Secret google recaptcha key
recaptcha_secret_key: "recaptchaSecretKey"

# The Youtube v3 Api key used to fetch video information
# from urls or to search for videos by search terms using /tv
youtube_api_key: "someYoutubeApiKey"

# Imgur client id
imgur_client_id: "someImgurID"

# Where the database of users and rooms reside
db_store_path: "/server/db/store"

# Internal path to were media files (user & rooms images etc) are stored
media_directory: "public/static"

# Interval of the loop (in minutes) to check for expired files
# that failed to be uploaded properly and delete them from memory
files_loop_delay: 30000

# Amount of time for file upload to be inactive for it to be considered expired
files_loop_max_diff: 20000

# Update the roomlist after these ms
roomlist_loop_delay: 300000

# Arbitrary big number to avoid big urls from being considered as valid room ids
max_room_id_length: 100

# The bigger the number the more the anti-spam system tolerates
anti_spam_max_limit: 100

# How much time in minutes a user is banned from the system after being detected
# as a spammer by the automatic spam detection system
anti_spam_ban_duration: 60

# Checks connections every x ms to unban and reduce levels
anti_spam_check_delay: 2000

# Block chat messages if spam level is >= to this
anti_spam_chat_limit: 20

# Add a spam every x chars of text
anti_spam_chat_chunks: 140

# Add a spam if last message was sent <= this ms
anti_spam_chat_delay: 2000

# The higher this number is, the slower it adds spam on file upload
upload_spam_charge: 550000

# The amount of time a session cookie is valid
# This cookie determines if a user needs to login again when entering
session_cookie_max_age: 987654321000

# This is used for the password hashing. A cost of 12 are 4096 salt rounds
# The more rounds, the more secure the hash is, but it takes longer to process
encryption_cost: 12

# How long jwt will be valid after login
jwt_expiration: 30000

# Max length of the jwt token
max_jwt_token_length: 300

# Maximum length for message ids (like chat message or media change ids)
max_message_id_length: 100

# After this length, this is clearly not a user id
max_user_id_length: 100

# Whether recaptcha verification is used at registration
recaptcha_enabled: true

# Maximum amount of data items allowed in socket emits
data_max_items: 20

# Used to check string data
data_items_max_string_length: 5000

# Used to check number data
data_items_max_number_length: 20

# How old link data has to be to be fetched again
redis_max_link_age: 604800000

# Maximum time to get a response when fetching link data
link_fetch_timeout: 10000

# After this the title from fetched link metadata gets cropped
link_max_title_length: 280

# After this the description from fetched link metadata gets cropped
link_max_description_length: 280

# After this the title from fetched link metadata gets ignored
link_max_image_length: 500

# Timeout for DB write file cache
db_write_file_timeout: 2000

# Max time without saving a file after a write call
db_write_file_timeout_limit: 10000

# Defaults to true for security reasons. If deployed in a non-https
# environment set it to false. In order for it to be really enabled 
# the Node environment must be set to production. If true, some non 
# https media will be blocked. It's recommended to setup a full https 
# site to conform to current standards. Check out Let's Encrypt
https_enabled: true

# The root url where the system will work. Needs a slash at the end
site_root: "https://hue.merkoba.com/"

# The default name of the main room
# Just like any room, this can be changed later
default_main_room_name: "Hue"

# The title of the login page
login_title: "Hue | Login"

# The title of the registration page.
register_title: "Hue | Register"

# The initial background color for new rooms
default_room_background_color: "#36393f"

# The initial text color for new rooms
default_room_text_color: "#eeeeec"

# Reserved username for system messages
system_username: "El Systema"

# The amount of minutes to wait between message
# board posts for non admin users
message_board_wait_delay: 5

# How many active sockets a user can have at the same time
# After this limit all incoming socket connections are dropped
max_sockets_per_user: 100

# How much it should wait in milliseconds before images can be 
# changed again after last change
image_change_cooldown: 2500

# How much it should wait in milliseconds before tv can be 
# changed again after last change
tv_change_cooldown: 2500

# Code to be able to register an account
# It can be an empty string to not require a code
register_code: "code_or_empty"