main_room_id: "main"
public_media_directory: "/static"
profilepic_loading_url: "/static/assets/img/profilepic_loading.png"
background_loading_url: "/static/assets/img/image_loading.jpg"
video_poster: "/static/assets/img/video_poster.jpg"
title_separator: " - "
default_title: "Hue | Chat room with images and tv"
default_topic: "No topic"
max_stored_image: 50
max_stored_tv: 50
media_changed_crop_limit: 500
notifications_crop_limit: 500
whispers_crop_limit: 500
chat_crop_limit: 500
input_history_crop_limit: 100
notifications_close_delay: 5000
max_whispers_post_length: 2000
max_media_info_length: 60
max_input_length: 2500
max_topic_length: 2000
max_username_length: 20
max_max_username_length: 300
min_password_length: 3
max_password_length: 200
max_max_password_length: 2000
max_room_name_length: 100
max_log_messages: 500
max_admin_log_messages: 250
max_message_board_posts: 250
max_message_board_post_length: 2000
upload_slice_size: 500000
max_media_source_length: 800
max_media_comment_length: 200
max_title_length: 280
max_image_size: 55555
max_tv_size: 55555
max_profilepic_size: 1111
max_audioclip_size: 9999
youtube_enabled: true
imgur_enabled: true
iframes_enabled: true
max_url_length: 1000

settings_default_highlight_current_username: true
settings_default_case_insensitive_username_highlights: true
settings_default_open_whispers_automatically: true
settings_default_embed_images: true
settings_default_show_link_previews: true
settings_default_show_highlight_notifications: true
settings_default_show_activity_notifications: true
settings_default_show_user_join_notifications: true
settings_default_show_user_leave_notifications: true
settings_default_stop_radio_on_tv_play: true
settings_default_stop_tv_on_radio_play: true
settings_default_confirm_on_close: false

room_state_default_image_enabled: true
room_state_default_tv_enabled: true
room_state_default_last_highlight_date: 0
room_state_default_chat_display_percentage: 40
room_state_default_tv_display_percentage: 60
room_state_default_tv_display_position: "bottom"
room_state_default_media_layout: "column"
room_state_default_main_layout: "row"
room_state_default_last_message_board_post: 0
room_state_default_chat_enabled: true
room_state_default_radio_volume: 1
room_state_default_radio_enabled: true
room_state_default_chat_font_size: 1
room_state_default_media_info_enabled: true
room_state_default_notifications_enabled: true
room_state_default_last_radio_name: ""

max_same_post_diff: 300000
max_same_post_messages: 20
socket_emit_throttle: 10

safe_limit_1: 100
safe_limit_2: 500
safe_limit_3: 1000
safe_limit_4: 200

profilepic_diameter: 300
max_num_newlines: 100
image_change_cooldown: 2500
tv_change_cooldown: 2500
max_sockets_per_user: 100
activity_bar_delay: 10000
max_activity_bar_items: 20
url_title_max_length: 35
max_whisper_users: 20
max_bio_length: 500
max_bio_lines: 4
max_info_popups: 5
commands_prefix: "/"
quote_max_length: 140
max_displayed_url: 65
max_activity_username_length: 8
chat_display_percentage_column: 60
chat_display_percentage_row: 40
screen_capture_durations: [5, 10, 30, 60]
image_blob_quality: 0.9
max_likes: 100

radios: 
  - name: Radio Name
    url: https://radiourl.net
    
  - name: Other Radio
    url: https://otheradio.com