# >The name of the main room. This is the room that will be joined
# when going to the root url. This room is created automatically when first joined
main_room_id: "main"

# Public location to access the media files
public_media_directory: "/static"

# Public location of reactions
reactions_directory: "/static/assets/img/reactions"

# The location of the loading image when the profile image is changing
profilepic_loading_url: "/static/assets/img/profilepic_loading.png"

# The location of the loading image when the background image is changing
background_loading_url: "/static/assets/img/image_loading.jpg"

# Image to show to video element when there's no video image loaded
video_poster: "/static/assets/img/video_poster.jpg"

# The default tab title of a room.
# This appears before the room information has been gathered to set the first title
default_title: "Multimedia chat room"

# The shown topic when the room is created
default_topic: "No topic"

# How many items are stored in images_changed and tv_changed
media_changed_crop_limit: 500

# How many notifications after the notifications items get cropped
# in the notifications window
notifications_crop_limit: 500

# Max number of whisper items to show
whispers_crop_limit: 500

# Max number of messages to keep on the client
chat_crop_limit: 500

# Automatically close notifications after these ms
notifications_close_delay: 5000

# Max length for whisper messages
max_whispers_post_length: 2000

# Maximum displayed media info
max_media_info_length: 200

# Maximum amount of text for something typed in the input box
# If something bigger is inputed it will get cropped to meet this limit
max_input_length: 2000

# The maximum length of a room topic. If a longer topic is tried to be set
# with /topic it will get cropped to meet this limit. /topicadd and
# /topicaddstart will throw an error if there is no more room to add to the topic
max_topic_length: 2000

# Maximum length for usernames
max_username_length: 20

# This is a safety used when validating usernames on login
# In case max or min username length configurations where changed
# when there were already users registered, this arbitrary big number
# is used to check something huge is not being inputed instead of checking
# with the username length configuration options, to avoid old username
# from not being able to login. This likely shouldn't be changed
max_max_username_length: 300

# Minimum length for passwords. It must be at least 1
min_password_length: 3

# Maximum length for passwords
max_password_length: 200

# Same as max_max_username_length but for passwords
max_max_password_length: 2000

# Max length for room names
max_room_name_length: 100

# Maximum amount of messages to store in room logs
# It stores chat messages and some notifications like image uploads and tv changes
max_log_messages: 500

# Maximum amount of messages to store in room admin logs
# It stores information about the most recent admin activity
max_admin_log_messages: 250

# How big the message board is. How many posts it stores
max_message_board_posts: 200

# How long message board posts can be
max_message_board_post_length: 2000

# The size of file slices to be uploaded
upload_slice_size: 500000

# Maximum length of a media source urls
max_media_source_length: 800

# Maximum length of comments on media change
max_media_comment_length: 200

# Maximum length for the tab's title. Title is the room_name
# and is set automatically. If title is bigger it gets cropped
max_title_length: 280

# Maximum image size allowed in KB. This is checked both in the client and server
# If the image is bigger it won't be uploaded
max_image_size: 55555

# Maximum video size allowed in KB. This is checked both in the client and server
# If the video is bigger it won't be uploaded
max_tv_size: 122222

# Maximum image size allowed for profile images
max_profilepic_size: 1111

# Maximum size allowed for user audio clips
max_audioclip_size: 9999

# Whether Youtube features are enabled
youtube_enabled: true

# Whether Imgur features are enabled
imgur_enabled: true

# Url lengths beyond this are ignored by the system
# This is to avoid triggering actions on urls
# that are likely wrong or meant as an attack
max_url_length: 1000

# Default user setting values
settings_default_highlight_current_username: true
settings_default_case_insensitive_username_highlights: true
settings_default_open_whispers_automatically: true
settings_default_embed_images: true
settings_default_show_link_previews: true
settings_default_show_highlight_notifications: true
settings_default_show_activity_notifications: true
settings_default_show_user_join_notifications: true
settings_default_show_user_leave_notifications: true
settings_default_show_background: true
settings_default_show_linksbar: true
settings_default_autoplay: true
settings_default_font: "sans-serif"
settings_default_chat_font_size: 1
settings_default_chat_size: 40
settings_default_main_layout: "row"
settings_default_media_layout: "column"
settings_default_tv_size: 60
settings_default_tv_position: "bottom"
settings_default_show_chat: true
settings_default_media_info: "normal"
settings_default_date_format: "relative"
settings_default_radio_auto_minutes: 15
settings_default_hide_scrollbars: true
settings_default_unread_count: true
settings_default_text_glow: false
settings_default_command_prefix: "/"
settings_default_open_message_board_automatically: true
settings_default_show_loaded: true
settings_default_show_clicked: true
settings_default_text_effects: true
settings_default_auto_blur: false

# Default room state values
room_state_default_image_enabled: true
room_state_default_tv_enabled: true
room_state_default_last_highlight_date: 0
room_state_default_last_message_board_post: 0
room_state_default_radio_volume: 1
room_state_default_notifications_enabled: true
room_state_default_last_radio_name: ""
room_state_default_radio_auto: false
room_state_default_last_input: ""

# Maximum difference in time between a message and and another
# from the same user to be displayed within the same post
max_same_post_diff: 300000

# Maximum messages within a post
# After this a new post is displayed
max_same_post_messages: 20

# Throttle on socket emits on the client
socket_emit_throttle: 10

# Generic limits used to check data length
safe_limit_1: 100
safe_limit_2: 500
safe_limit_3: 1000
safe_limit_4: 200

# The diameter of the cropped profile image selected by the user
profilepic_diameter: 300

# Maximum amount of newlines allowed per message
max_num_newlines: 100

# How often to check for obsolete items in the top activity bar to remove them
activity_bar_delay: 10000

# Maximum amount of top activity bar items at the same time
max_activity_bar_items: 20

# Max number of whisper receivers
max_whisper_users: 20

# Character length of user bios
max_bio_length: 500

# Maximum number of linebreaks allowed in user bios
max_bio_lines: 4

# How many info popups (bottom right) can be displayed at once
# After this, the older ones get closed
max_info_popups: 5

# How long the reply quote can be
quote_max_length: 140

# Max length of urls in chat
max_displayed_url: 100

# How wide usernames on the activity bar can be
max_activity_username_length: 8

# How long in seconds tv screen capture videos can be
screen_capture_durations: [5, 10, 20, 30, 60]

# Quality for rendered image blobs
image_blob_quality: 0.9

# The max amount of likes a message can register
max_likes: 100

# The max amount of input history to remember
max_input_history: 100

# Max message length when making custom notifications
max_notification_length: 500

# Max autocomplete words to save
# It saves words that start with a symbol like .this or !that
# The aim is to store bot commands for easy access
max_autocomplete: 1000

# Show loginfo messages on the console
loginfo: false

# Radio stations available
radios:
  - name: Anima Dub Techno
    url: http://amoris.sknt.ru/dubtechno.mp3

  - name: Anima Electronic Styles
    url: http://amoris.sknt.ru/electronic.mp3

  - name: Anima Goa Psy Trance
    url: http://amoris.sknt.ru/goa.mp3

  - name: Anima Dub Step
    url: http://amoris.sknt.ru/dubstep.mp3

  - name: Anima Drum and Bass
    url: http://amoris.sknt.ru/dnb.mp3

  - name: Anima Minimal Deep Techno
    url: http://amoris.sknt.ru/minimal.mp3

  - name: Anima Deep Tech House
    url: http://amoris.sknt.ru/deeptech.mp3

  - name: Anima Ambient
    url: http://amoris.sknt.ru/ambient.mp3

  - name: Anima IDM
    url: http://amoris.sknt.ru/idm.mp3

  - name: Anima New Age
    url: http://amoris.sknt.ru/newage.mp3

  - name: Anima Trip Hop Lounge
    url: http://amoris.sknt.ru/triphop.mp3

  - name: Anima Techno
    url: http://amoris.sknt.ru/techno.mp3

  - name: Anima Dub Techno Mix
    url: http://amoris.sknt.ru/dubtechnomix.mp3

  - name: Anima Electro
    url: http://amoris.sknt.ru/electro.mp3

  - name: Rekt Network
    url: https://stream.rekt.network/rekt.mp3

  - name: Le Son Parisien
    url: http://stream.lesonparisien.com/mid

  - name: Channel 1
    url: http://stream.tilos.hu/karolyi-chill-eclectic